// Generated by CoffeeScript 1.7.1
(function() {
  var CanMessage, charm, colors, d, data, i, msg, pair, _i, _j, _len, _len1, _ref;

  charm = require('charm')();

  charm.pipe(process.stdout);

  charm.reset();

  colors = ['red', 'cyan', 'yellow', 'green', 'blue'];

  data = ['6210108A00000000000', '06000005E', '13080', '2100040000600040008', '220410000BC00000048', '2302001', '09100000000', '32001100000000000', '4600000AF6EFF', '37000800000', '6220100400000000000', '380000000000000'];

  CanMessage = (function() {
    function CanMessage(message) {
      this.arbId = message.slice(0, 3);
      this.data = message.slice(3);
    }

    CanMessage.prototype.charData = function() {
      var byte, int, str, _i, _len, _ref;
      str = '';
      _ref = this.dataPairs();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        byte = _ref[_i];
        int = parseInt(byte, 16);
        if ((33 <= int && int <= 126)) {
          str = "" + str + (String.fromCharCode(int));
        } else {
          str = "" + str + ".";
        }
      }
      return str;
    };

    CanMessage.prototype.dataPairs = function() {
      return this.data.match(/.{2}/g);
    };

    CanMessage.prototype.toString = function() {
      return "" + this.arbId + ": " + this.data + " " + (this.charData());
    };

    return CanMessage;

  })();

  for (i = _i = 0, _len = data.length; _i < _len; i = ++_i) {
    d = data[i];
    msg = new CanMessage(d);
    charm.position(0, i + 1).foreground('blue').write(msg.arbId).right(1).foreground('green');
    _ref = msg.dataPairs();
    for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
      pair = _ref[_j];
      charm.write(pair).right(1);
    }
    charm.foreground('red').position(40, i + 1).write(msg.charData());
  }

}).call(this);
